# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\EditType.ui'
#
# Created: Sun May 27 23:28:59 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DgEditType(object):
    def setupUi(self, DgEditType):
        DgEditType.setObjectName(_fromUtf8("DgEditType"))
        DgEditType.resize(417, 530)
        self.verticalLayout = QtGui.QVBoxLayout(DgEditType)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(DgEditType)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lEdName = QtGui.QLineEdit(DgEditType)
        self.lEdName.setObjectName(_fromUtf8("lEdName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lEdName)
        self.line = QtGui.QFrame(DgEditType)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line)
        self.label_2 = QtGui.QLabel(DgEditType)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setIndent(2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lbSendAfterReceive = QtGui.QLabel(DgEditType)
        self.lbSendAfterReceive.setObjectName(_fromUtf8("lbSendAfterReceive"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbSendAfterReceive)
        self.cbxSendAfterReceive = QtGui.QCheckBox(DgEditType)
        self.cbxSendAfterReceive.setText(_fromUtf8(""))
        self.cbxSendAfterReceive.setObjectName(_fromUtf8("cbxSendAfterReceive"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbxSendAfterReceive)
        self.lbIncludeBehavior = QtGui.QLabel(DgEditType)
        self.lbIncludeBehavior.setObjectName(_fromUtf8("lbIncludeBehavior"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbIncludeBehavior)
        self.cbxIncludeBehavior = QtGui.QCheckBox(DgEditType)
        self.cbxIncludeBehavior.setText(_fromUtf8(""))
        self.cbxIncludeBehavior.setObjectName(_fromUtf8("cbxIncludeBehavior"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbxIncludeBehavior)
        self.lbProcess = QtGui.QLabel(DgEditType)
        self.lbProcess.setObjectName(_fromUtf8("lbProcess"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbProcess)
        self.cmbxProcess = QtGui.QComboBox(DgEditType)
        self.cmbxProcess.setObjectName(_fromUtf8("cmbxProcess"))
        self.cmbxProcess.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cmbxProcess)
        self.lbLearn = QtGui.QLabel(DgEditType)
        self.lbLearn.setObjectName(_fromUtf8("lbLearn"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbLearn)
        self.cmbxLearn = QtGui.QComboBox(DgEditType)
        self.cmbxLearn.setObjectName(_fromUtf8("cmbxLearn"))
        self.cmbxLearn.addItem(_fromUtf8(""))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cmbxLearn)
        self.lbRoute = QtGui.QLabel(DgEditType)
        self.lbRoute.setObjectName(_fromUtf8("lbRoute"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbRoute)
        self.cmbxRoute = QtGui.QComboBox(DgEditType)
        self.cmbxRoute.setObjectName(_fromUtf8("cmbxRoute"))
        self.cmbxRoute.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cmbxRoute)
        self.lbSelect = QtGui.QLabel(DgEditType)
        self.lbSelect.setObjectName(_fromUtf8("lbSelect"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lbSelect)
        self.cmbxSelect = QtGui.QComboBox(DgEditType)
        self.cmbxSelect.setObjectName(_fromUtf8("cmbxSelect"))
        self.cmbxSelect.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.cmbxSelect)
        self.lbTransform = QtGui.QLabel(DgEditType)
        self.lbTransform.setObjectName(_fromUtf8("lbTransform"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.lbTransform)
        self.cmbxTransform = QtGui.QComboBox(DgEditType)
        self.cmbxTransform.setObjectName(_fromUtf8("cmbxTransform"))
        self.cmbxTransform.addItem(_fromUtf8(""))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.cmbxTransform)
        self.lbCleanup = QtGui.QLabel(DgEditType)
        self.lbCleanup.setObjectName(_fromUtf8("lbCleanup"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.lbCleanup)
        self.cmbxCleanup = QtGui.QComboBox(DgEditType)
        self.cmbxCleanup.setObjectName(_fromUtf8("cmbxCleanup"))
        self.cmbxCleanup.addItem(_fromUtf8(""))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cmbxCleanup)
        self.lbOnSignal = QtGui.QLabel(DgEditType)
        self.lbOnSignal.setObjectName(_fromUtf8("lbOnSignal"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.lbOnSignal)
        self.cmbxOnSignal = QtGui.QComboBox(DgEditType)
        self.cmbxOnSignal.setObjectName(_fromUtf8("cmbxOnSignal"))
        self.cmbxOnSignal.addItem(_fromUtf8(""))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.cmbxOnSignal)
        self.line_2 = QtGui.QFrame(DgEditType)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.label_4 = QtGui.QLabel(DgEditType)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setIndent(1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cbxAtColor = QtGui.QCheckBox(DgEditType)
        self.cbxAtColor.setEnabled(True)
        self.cbxAtColor.setCheckable(False)
        self.cbxAtColor.setObjectName(_fromUtf8("cbxAtColor"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.cbxAtColor)
        self.btnColor = QtGui.QPushButton(DgEditType)
        self.btnColor.setObjectName(_fromUtf8("btnColor"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.btnColor)
        self.verticalLayout.addLayout(self.formLayout)
        self.line_4 = QtGui.QFrame(DgEditType)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnRemove = QtGui.QPushButton(DgEditType)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.btnAdd = QtGui.QPushButton(DgEditType)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtGui.QFrame(DgEditType)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnDelete = QtGui.QPushButton(DgEditType)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnClone = QtGui.QPushButton(DgEditType)
        self.btnClone.setObjectName(_fromUtf8("btnClone"))
        self.horizontalLayout.addWidget(self.btnClone)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnCancel = QtGui.QPushButton(DgEditType)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(DgEditType)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DgEditType)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), DgEditType.accept)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), DgEditType.reject)
        QtCore.QMetaObject.connectSlotsByName(DgEditType)

    def retranslateUi(self, DgEditType):
        DgEditType.setWindowTitle(QtGui.QApplication.translate("DgEditType", "Edit Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DgEditType", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DgEditType", "Behaviour:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbSendAfterReceive.setText(QtGui.QApplication.translate("DgEditType", "Send After Receive:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbIncludeBehavior.setText(QtGui.QApplication.translate("DgEditType", "Include Behavior:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbProcess.setText(QtGui.QApplication.translate("DgEditType", "Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxProcess.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbLearn.setText(QtGui.QApplication.translate("DgEditType", "Learn:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxLearn.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbRoute.setText(QtGui.QApplication.translate("DgEditType", "Route:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxRoute.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbSelect.setText(QtGui.QApplication.translate("DgEditType", "Select:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSelect.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTransform.setText(QtGui.QApplication.translate("DgEditType", "Transform:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxTransform.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbCleanup.setText(QtGui.QApplication.translate("DgEditType", "Cleanup:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxCleanup.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOnSignal.setText(QtGui.QApplication.translate("DgEditType", "On Signal:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxOnSignal.setItemText(0, QtGui.QApplication.translate("DgEditType", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DgEditType", "Attributes:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAtColor.setText(QtGui.QApplication.translate("DgEditType", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btnColor.setText(QtGui.QApplication.translate("DgEditType", "Select Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("DgEditType", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("DgEditType", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("DgEditType", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClone.setText(QtGui.QApplication.translate("DgEditType", "&Clone", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("DgEditType", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("DgEditType", "&Ok", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FunctionViewer.ui'
#
# Created: Sun May 27 23:28:59 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DgFuntions(object):
    def setupUi(self, DgFuntions):
        DgFuntions.setObjectName(_fromUtf8("DgFuntions"))
        DgFuntions.resize(693, 453)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DgFuntions)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(DgFuntions)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 330, 346))
        self.page.setObjectName(_fromUtf8("page"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnRemove = QtGui.QPushButton(self.layoutWidget)
        self.btnRemove.setEnabled(False)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.horizontalLayout.addWidget(self.btnRemove)
        self.btnAdd = QtGui.QPushButton(self.layoutWidget)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.functionView = QtGui.QGraphicsView(self.splitter)
        self.functionView.setObjectName(_fromUtf8("functionView"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.buttonBox = QtGui.QDialogButtonBox(DgFuntions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DgFuntions)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DgFuntions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DgFuntions.reject)
        QtCore.QMetaObject.connectSlotsByName(DgFuntions)

    def retranslateUi(self, DgFuntions):
        DgFuntions.setWindowTitle(QtGui.QApplication.translate("DgFuntions", "Function Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("DgFuntions", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("DgFuntions", "&Remove Value", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("DgFuntions", "&Add Value", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GraphViewer.ui'
#
# Created: Sun May 27 23:28:59 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GraphViewer(object):
    def setupUi(self, GraphViewer):
        GraphViewer.setObjectName(_fromUtf8("GraphViewer"))
        GraphViewer.resize(1013, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Clique.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GraphViewer.setWindowIcon(icon)
        GraphViewer.setIconSize(QtCore.QSize(32, 32))
        GraphViewer.setAnimated(True)
        GraphViewer.setDockNestingEnabled(True)
        GraphViewer.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(GraphViewer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.graphicsView.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.graphicsView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QtGui.QGraphicsView.BoundingRectViewportUpdate)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        GraphViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GraphViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTransform = QtGui.QMenu(self.menubar)
        self.menuTransform.setObjectName(_fromUtf8("menuTransform"))
        self.menuDefault_Node_Type = QtGui.QMenu(self.menuTransform)
        self.menuDefault_Node_Type.setObjectName(_fromUtf8("menuDefault_Node_Type"))
        self.menuInsert = QtGui.QMenu(self.menubar)
        self.menuInsert.setObjectName(_fromUtf8("menuInsert"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Viewport = QtGui.QMenu(self.menu_View)
        self.menu_Viewport.setObjectName(_fromUtf8("menu_Viewport"))
        self.menuRender_Hints = QtGui.QMenu(self.menu_Viewport)
        self.menuRender_Hints.setObjectName(_fromUtf8("menuRender_Hints"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menu_Layout = QtGui.QMenu(self.menubar)
        self.menu_Layout.setObjectName(_fromUtf8("menu_Layout"))
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName(_fromUtf8("menu_Window"))
        self.menu_Node_Types = QtGui.QMenu(self.menubar)
        self.menu_Node_Types.setObjectName(_fromUtf8("menu_Node_Types"))
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        GraphViewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GraphViewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        GraphViewer.setStatusBar(self.statusbar)
        self.toolBoxDock = QtGui.QDockWidget(GraphViewer)
        self.toolBoxDock.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxDock.sizePolicy().hasHeightForWidth())
        self.toolBoxDock.setSizePolicy(sizePolicy)
        self.toolBoxDock.setMinimumSize(QtCore.QSize(320, 190))
        self.toolBoxDock.setFloating(False)
        self.toolBoxDock.setObjectName(_fromUtf8("toolBoxDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pageModes = QtGui.QWidget()
        self.pageModes.setGeometry(QtCore.QRect(0, 0, 285, 466))
        self.pageModes.setObjectName(_fromUtf8("pageModes"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageModes)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnSelection = QtGui.QCommandLinkButton(self.pageModes)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelection.setIcon(icon1)
        self.btnSelection.setIconSize(QtCore.QSize(42, 42))
        self.btnSelection.setCheckable(True)
        self.btnSelection.setChecked(True)
        self.btnSelection.setObjectName(_fromUtf8("btnSelection"))
        self.buttonGroup = QtGui.QButtonGroup(GraphViewer)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.btnSelection)
        self.verticalLayout_2.addWidget(self.btnSelection)
        self.btnAddNode = QtGui.QCommandLinkButton(self.pageModes)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Create.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddNode.setIcon(icon2)
        self.btnAddNode.setIconSize(QtCore.QSize(42, 42))
        self.btnAddNode.setCheckable(True)
        self.btnAddNode.setObjectName(_fromUtf8("btnAddNode"))
        self.buttonGroup.addButton(self.btnAddNode)
        self.verticalLayout_2.addWidget(self.btnAddNode)
        self.btnClique = QtGui.QCommandLinkButton(self.pageModes)
        self.btnClique.setIcon(icon)
        self.btnClique.setIconSize(QtCore.QSize(42, 42))
        self.btnClique.setCheckable(True)
        self.btnClique.setObjectName(_fromUtf8("btnClique"))
        self.buttonGroup.addButton(self.btnClique)
        self.verticalLayout_2.addWidget(self.btnClique)
        self.btnCycle = QtGui.QCommandLinkButton(self.pageModes)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Cycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCycle.setIcon(icon3)
        self.btnCycle.setIconSize(QtCore.QSize(42, 42))
        self.btnCycle.setCheckable(True)
        self.btnCycle.setObjectName(_fromUtf8("btnCycle"))
        self.buttonGroup.addButton(self.btnCycle)
        self.verticalLayout_2.addWidget(self.btnCycle)
        self.btnPath = QtGui.QCommandLinkButton(self.pageModes)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Path.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPath.setIcon(icon4)
        self.btnPath.setIconSize(QtCore.QSize(42, 42))
        self.btnPath.setCheckable(True)
        self.btnPath.setObjectName(_fromUtf8("btnPath"))
        self.buttonGroup.addButton(self.btnPath)
        self.verticalLayout_2.addWidget(self.btnPath)
        self.btnConnect = QtGui.QCommandLinkButton(self.pageModes)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConnect.setIcon(icon5)
        self.btnConnect.setIconSize(QtCore.QSize(42, 42))
        self.btnConnect.setCheckable(True)
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.buttonGroup.addButton(self.btnConnect)
        self.verticalLayout_2.addWidget(self.btnConnect)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.toolBox.addItem(self.pageModes, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.toolBox)
        self.toolBoxDock.setWidget(self.dockWidgetContents)
        GraphViewer.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.toolBoxDock)
        self.modesToolbar = QtGui.QToolBar(GraphViewer)
        self.modesToolbar.setIconSize(QtCore.QSize(42, 42))
        self.modesToolbar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.modesToolbar.setObjectName(_fromUtf8("modesToolbar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.modesToolbar)
        self.graphDock = QtGui.QDockWidget(GraphViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphDock.sizePolicy().hasHeightForWidth())
        self.graphDock.setSizePolicy(sizePolicy)
        self.graphDock.setMinimumSize(QtCore.QSize(320, 136))
        self.graphDock.setObjectName(_fromUtf8("graphDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.graphToolBox = QtGui.QToolBox(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphToolBox.sizePolicy().hasHeightForWidth())
        self.graphToolBox.setSizePolicy(sizePolicy)
        self.graphToolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.graphToolBox.setObjectName(_fromUtf8("graphToolBox"))
        self.pageBasic = QtGui.QWidget()
        self.pageBasic.setGeometry(QtCore.QRect(0, 0, 302, 69))
        self.pageBasic.setObjectName(_fromUtf8("pageBasic"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pageBasic)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.graphToolBox.addItem(self.pageBasic, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.graphToolBox, 0, 0, 1, 1)
        self.graphDock.setWidget(self.dockWidgetContents_2)
        GraphViewer.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.graphDock)
        self.designToolbar = QtGui.QToolBar(GraphViewer)
        self.designToolbar.setIconSize(QtCore.QSize(42, 42))
        self.designToolbar.setObjectName(_fromUtf8("designToolbar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.designToolbar)
        self.deleteToolbar = QtGui.QToolBar(GraphViewer)
        self.deleteToolbar.setIconSize(QtCore.QSize(42, 42))
        self.deleteToolbar.setObjectName(_fromUtf8("deleteToolbar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.deleteToolbar)
        self.bipartiteToolbar = QtGui.QToolBar(GraphViewer)
        self.bipartiteToolbar.setIconSize(QtCore.QSize(42, 42))
        self.bipartiteToolbar.setObjectName(_fromUtf8("bipartiteToolbar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.bipartiteToolbar)
        self.edgesToolbar = QtGui.QToolBar(GraphViewer)
        self.edgesToolbar.setIconSize(QtCore.QSize(42, 42))
        self.edgesToolbar.setObjectName(_fromUtf8("edgesToolbar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.edgesToolbar)
        self.graphView = QtGui.QDockWidget(GraphViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphView.sizePolicy().hasHeightForWidth())
        self.graphView.setSizePolicy(sizePolicy)
        self.graphView.setMinimumSize(QtCore.QSize(250, 111))
        self.graphView.setObjectName(_fromUtf8("graphView"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphTree = QtGui.QTreeWidget(self.dockWidgetContents_4)
        self.graphTree.setObjectName(_fromUtf8("graphTree"))
        self.verticalLayout_3.addWidget(self.graphTree)
        self.graphView.setWidget(self.dockWidgetContents_4)
        GraphViewer.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.graphView)
        self.toolBar = QtGui.QToolBar(GraphViewer)
        self.toolBar.setIconSize(QtCore.QSize(42, 42))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        GraphViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(GraphViewer)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.console = QtGui.QPlainTextEdit(self.dockWidgetContents_3)
        self.console.setUndoRedoEnabled(False)
        self.console.setObjectName(_fromUtf8("console"))
        self.horizontalLayout_2.addWidget(self.console)
        self.dockWidget.setWidget(self.dockWidgetContents_3)
        GraphViewer.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionSelection = QtGui.QAction(GraphViewer)
        self.actionSelection.setCheckable(True)
        self.actionSelection.setChecked(True)
        self.actionSelection.setIcon(icon1)
        self.actionSelection.setObjectName(_fromUtf8("actionSelection"))
        self.actionCreation = QtGui.QAction(GraphViewer)
        self.actionCreation.setCheckable(True)
        self.actionCreation.setChecked(False)
        self.actionCreation.setIcon(icon2)
        self.actionCreation.setObjectName(_fromUtf8("actionCreation"))
        self.actionQuit = QtGui.QAction(GraphViewer)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionClique = QtGui.QAction(GraphViewer)
        self.actionClique.setCheckable(True)
        self.actionClique.setIcon(icon)
        self.actionClique.setObjectName(_fromUtf8("actionClique"))
        self.actionCycle = QtGui.QAction(GraphViewer)
        self.actionCycle.setCheckable(True)
        self.actionCycle.setIcon(icon3)
        self.actionCycle.setObjectName(_fromUtf8("actionCycle"))
        self.actionMakeClique = QtGui.QAction(GraphViewer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/MakeClique.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMakeClique.setIcon(icon6)
        self.actionMakeClique.setObjectName(_fromUtf8("actionMakeClique"))
        self.actionMakeCycle = QtGui.QAction(GraphViewer)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/MakeCycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMakeCycle.setIcon(icon7)
        self.actionMakeCycle.setObjectName(_fromUtf8("actionMakeCycle"))
        self.actionMakePath = QtGui.QAction(GraphViewer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/MakePath.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMakePath.setIcon(icon8)
        self.actionMakePath.setObjectName(_fromUtf8("actionMakePath"))
        self.actionPath = QtGui.QAction(GraphViewer)
        self.actionPath.setCheckable(True)
        self.actionPath.setIcon(icon4)
        self.actionPath.setObjectName(_fromUtf8("actionPath"))
        self.actionRemoveAll = QtGui.QAction(GraphViewer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/RemoveAll.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveAll.setIcon(icon9)
        self.actionRemoveAll.setObjectName(_fromUtf8("actionRemoveAll"))
        self.actionRemoveEdges = QtGui.QAction(GraphViewer)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/RemoveEdges.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveEdges.setIcon(icon10)
        self.actionRemoveEdges.setObjectName(_fromUtf8("actionRemoveEdges"))
        self.actionSwapEdges = QtGui.QAction(GraphViewer)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/SwapEdges.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSwapEdges.setIcon(icon11)
        self.actionSwapEdges.setObjectName(_fromUtf8("actionSwapEdges"))
        self.actionCompleteEdges = QtGui.QAction(GraphViewer)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/CompleteEdges.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompleteEdges.setIcon(icon12)
        self.actionCompleteEdges.setObjectName(_fromUtf8("actionCompleteEdges"))
        self.actionLeftBipartite = QtGui.QAction(GraphViewer)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/LeftBipartite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeftBipartite.setIcon(icon13)
        self.actionLeftBipartite.setObjectName(_fromUtf8("actionLeftBipartite"))
        self.actionCompleteBipartite = QtGui.QAction(GraphViewer)
        self.actionCompleteBipartite.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/RightBipartite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompleteBipartite.setIcon(icon14)
        self.actionCompleteBipartite.setObjectName(_fromUtf8("actionCompleteBipartite"))
        self.actionGlViewport = QtGui.QAction(GraphViewer)
        self.actionGlViewport.setCheckable(True)
        self.actionGlViewport.setObjectName(_fromUtf8("actionGlViewport"))
        self.actionStandardViewport = QtGui.QAction(GraphViewer)
        self.actionStandardViewport.setCheckable(True)
        self.actionStandardViewport.setChecked(True)
        self.actionStandardViewport.setObjectName(_fromUtf8("actionStandardViewport"))
        self.actionAnimations = QtGui.QAction(GraphViewer)
        self.actionAnimations.setCheckable(True)
        self.actionAnimations.setChecked(False)
        self.actionAnimations.setObjectName(_fromUtf8("actionAnimations"))
        self.actionAntialiasing = QtGui.QAction(GraphViewer)
        self.actionAntialiasing.setCheckable(True)
        self.actionAntialiasing.setChecked(True)
        self.actionAntialiasing.setObjectName(_fromUtf8("actionAntialiasing"))
        self.actionText_Antialiasing = QtGui.QAction(GraphViewer)
        self.actionText_Antialiasing.setCheckable(True)
        self.actionText_Antialiasing.setChecked(True)
        self.actionText_Antialiasing.setObjectName(_fromUtf8("actionText_Antialiasing"))
        self.actionSmooth_Pixmap_Transform = QtGui.QAction(GraphViewer)
        self.actionSmooth_Pixmap_Transform.setCheckable(True)
        self.actionSmooth_Pixmap_Transform.setObjectName(_fromUtf8("actionSmooth_Pixmap_Transform"))
        self.actionHigh_Quality_Antialiasing = QtGui.QAction(GraphViewer)
        self.actionHigh_Quality_Antialiasing.setCheckable(True)
        self.actionHigh_Quality_Antialiasing.setObjectName(_fromUtf8("actionHigh_Quality_Antialiasing"))
        self.actionConnect = QtGui.QAction(GraphViewer)
        self.actionConnect.setCheckable(True)
        self.actionConnect.setIcon(icon5)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.action_Function_Viewer = QtGui.QAction(GraphViewer)
        self.action_Function_Viewer.setObjectName(_fromUtf8("action_Function_Viewer"))
        self.actionStandard = QtGui.QAction(GraphViewer)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Standard Node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandard.setIcon(icon15)
        self.actionStandard.setObjectName(_fromUtf8("actionStandard"))
        self.actionPlay = QtGui.QAction(GraphViewer)
        self.actionPlay.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Inactive Play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Play.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Play.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon16)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(GraphViewer)
        self.actionPause.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Inactive Pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Pause.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Pause.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Pause.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon17)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionJump = QtGui.QAction(GraphViewer)
        self.actionJump.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Inactive Jump.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Jump.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Jump.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Jump.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionJump.setIcon(icon18)
        self.actionJump.setObjectName(_fromUtf8("actionJump"))
        self.actionNext = QtGui.QAction(GraphViewer)
        self.actionNext.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("../Resources/Inactive Play Pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Play Pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Play Pause.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/Inactive Play Pause.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon19)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionAddType = QtGui.QAction(GraphViewer)
        self.actionAddType.setObjectName(_fromUtf8("actionAddType"))
        self.actionStandardNode = QtGui.QAction(GraphViewer)
        self.actionStandardNode.setCheckable(True)
        self.actionStandardNode.setChecked(True)
        self.actionStandardNode.setObjectName(_fromUtf8("actionStandardNode"))
        self.menuFile.addAction(self.actionQuit)
        self.menuDefault_Node_Type.addAction(self.actionStandardNode)
        self.menuTransform.addAction(self.menuDefault_Node_Type.menuAction())
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionSelection)
        self.menuTransform.addAction(self.actionCreation)
        self.menuTransform.addAction(self.actionClique)
        self.menuTransform.addAction(self.actionCycle)
        self.menuTransform.addAction(self.actionPath)
        self.menuTransform.addAction(self.actionConnect)
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionMakeClique)
        self.menuTransform.addAction(self.actionMakeCycle)
        self.menuTransform.addAction(self.actionMakePath)
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionLeftBipartite)
        self.menuTransform.addAction(self.actionCompleteBipartite)
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionRemoveAll)
        self.menuTransform.addAction(self.actionRemoveEdges)
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionSwapEdges)
        self.menuTransform.addAction(self.actionCompleteEdges)
        self.menuRender_Hints.addAction(self.actionAntialiasing)
        self.menuRender_Hints.addAction(self.actionText_Antialiasing)
        self.menuRender_Hints.addAction(self.actionSmooth_Pixmap_Transform)
        self.menuRender_Hints.addAction(self.actionHigh_Quality_Antialiasing)
        self.menu_Viewport.addAction(self.actionGlViewport)
        self.menu_Viewport.addAction(self.actionStandardViewport)
        self.menu_Viewport.addSeparator()
        self.menu_Viewport.addAction(self.menuRender_Hints.menuAction())
        self.menu_View.addAction(self.actionAnimations)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.menu_Viewport.menuAction())
        self.menu_Window.addAction(self.action_Function_Viewer)
        self.menu_Node_Types.addAction(self.actionAddType)
        self.menu_Node_Types.addSeparator()
        self.menu_Node_Types.addAction(self.actionStandard)
        self.menuSimulation.addAction(self.actionPlay)
        self.menuSimulation.addAction(self.actionPause)
        self.menuSimulation.addAction(self.actionNext)
        self.menuSimulation.addAction(self.actionJump)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuTransform.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menu_Layout.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menu_Node_Types.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.modesToolbar.addAction(self.actionSelection)
        self.modesToolbar.addAction(self.actionCreation)
        self.modesToolbar.addAction(self.actionClique)
        self.modesToolbar.addAction(self.actionCycle)
        self.modesToolbar.addAction(self.actionPath)
        self.modesToolbar.addAction(self.actionConnect)
        self.designToolbar.addAction(self.actionMakeClique)
        self.designToolbar.addAction(self.actionMakeCycle)
        self.designToolbar.addAction(self.actionMakePath)
        self.deleteToolbar.addAction(self.actionRemoveAll)
        self.deleteToolbar.addAction(self.actionRemoveEdges)
        self.bipartiteToolbar.addAction(self.actionLeftBipartite)
        self.bipartiteToolbar.addAction(self.actionCompleteBipartite)
        self.edgesToolbar.addAction(self.actionSwapEdges)
        self.edgesToolbar.addAction(self.actionCompleteEdges)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionJump)

        self.retranslateUi(GraphViewer)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        self.graphToolBox.setCurrentIndex(0)
        self.graphToolBox.layout().setSpacing(6)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), GraphViewer.close)
        QtCore.QObject.connect(self.btnSelection, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionSelection.setChecked)
        QtCore.QObject.connect(self.btnAddNode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.actionCreation.setChecked)
        QtCore.QObject.connect(self.btnClique, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.actionClique.setChecked)
        QtCore.QObject.connect(self.btnCycle, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.actionCycle.setChecked)
        QtCore.QObject.connect(self.btnPath, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.actionPath.setChecked)
        QtCore.QObject.connect(self.actionSelection, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnSelection.setChecked)
        QtCore.QObject.connect(self.actionCreation, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnAddNode.setChecked)
        QtCore.QObject.connect(self.actionClique, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnClique.setChecked)
        QtCore.QObject.connect(self.actionCycle, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnCycle.setChecked)
        QtCore.QObject.connect(self.actionPath, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnPath.setChecked)
        QtCore.QObject.connect(self.btnConnect, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionConnect.setChecked)
        QtCore.QObject.connect(self.actionConnect, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnConnect.setChecked)
        QtCore.QMetaObject.connectSlotsByName(GraphViewer)

    def retranslateUi(self, GraphViewer):
        GraphViewer.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("GraphViewer", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTransform.setTitle(QtGui.QApplication.translate("GraphViewer", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDefault_Node_Type.setTitle(QtGui.QApplication.translate("GraphViewer", "Default Node Type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInsert.setTitle(QtGui.QApplication.translate("GraphViewer", "&Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("GraphViewer", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Viewport.setTitle(QtGui.QApplication.translate("GraphViewer", "&Viewport", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRender_Hints.setTitle(QtGui.QApplication.translate("GraphViewer", "Render Hints", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlugins.setTitle(QtGui.QApplication.translate("GraphViewer", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Layout.setTitle(QtGui.QApplication.translate("GraphViewer", "&Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("GraphViewer", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Node_Types.setTitle(QtGui.QApplication.translate("GraphViewer", "&Node Types", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("GraphViewer", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDock.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Toolbox", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelection.setText(QtGui.QApplication.translate("GraphViewer", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelection.setDescription(QtGui.QApplication.translate("GraphViewer", "Select multiple nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddNode.setText(QtGui.QApplication.translate("GraphViewer", "Add Node", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddNode.setDescription(QtGui.QApplication.translate("GraphViewer", "Add independent nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClique.setText(QtGui.QApplication.translate("GraphViewer", "Create Clique", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClique.setDescription(QtGui.QApplication.translate("GraphViewer", "Add nodes to create a clique", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCycle.setText(QtGui.QApplication.translate("GraphViewer", "Create Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCycle.setDescription(QtGui.QApplication.translate("GraphViewer", "Add nodes to create a cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPath.setText(QtGui.QApplication.translate("GraphViewer", "Create Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPath.setDescription(QtGui.QApplication.translate("GraphViewer", "Add nodes to create a path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("GraphViewer", "Connect Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setDescription(QtGui.QApplication.translate("GraphViewer", "Click on nodes to create edges", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageModes), QtGui.QApplication.translate("GraphViewer", "Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.modesToolbar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Modes Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.graphDock.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.graphToolBox.setItemText(self.graphToolBox.indexOf(self.pageBasic), QtGui.QApplication.translate("GraphViewer", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.designToolbar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Design Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteToolbar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Remove Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.bipartiteToolbar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Bipartite Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.edgesToolbar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Edges Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.graphView.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Graph Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.graphTree.headerItem().setText(0, QtGui.QApplication.translate("GraphViewer", "Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("GraphViewer", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelection.setText(QtGui.QApplication.translate("GraphViewer", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelection.setToolTip(QtGui.QApplication.translate("GraphViewer", "Allows to select several nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelection.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreation.setText(QtGui.QApplication.translate("GraphViewer", "Add Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreation.setToolTip(QtGui.QApplication.translate("GraphViewer", "Adds a new node with double click", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreation.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("GraphViewer", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("GraphViewer", "Exit the graph creation tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("GraphViewer", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClique.setText(QtGui.QApplication.translate("GraphViewer", "Clique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClique.setToolTip(QtGui.QApplication.translate("GraphViewer", "New nodes will make a clique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClique.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCycle.setText(QtGui.QApplication.translate("GraphViewer", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCycle.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeClique.setText(QtGui.QApplication.translate("GraphViewer", "Make Clique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeClique.setToolTip(QtGui.QApplication.translate("GraphViewer", "Makes a clique from all selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeClique.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeCycle.setText(QtGui.QApplication.translate("GraphViewer", "Make Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeCycle.setToolTip(QtGui.QApplication.translate("GraphViewer", "Makes a cycle between all selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakeCycle.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakePath.setText(QtGui.QApplication.translate("GraphViewer", "Make Path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakePath.setToolTip(QtGui.QApplication.translate("GraphViewer", "Makes a path between all selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMakePath.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPath.setText(QtGui.QApplication.translate("GraphViewer", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPath.setToolTip(QtGui.QApplication.translate("GraphViewer", "Allows to build a path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPath.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveAll.setText(QtGui.QApplication.translate("GraphViewer", "Remove All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveAll.setToolTip(QtGui.QApplication.translate("GraphViewer", "Deletes all nodes selected and all related edges", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveAll.setShortcut(QtGui.QApplication.translate("GraphViewer", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveEdges.setText(QtGui.QApplication.translate("GraphViewer", "Remove Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveEdges.setToolTip(QtGui.QApplication.translate("GraphViewer", "Deletes all edges between any pair of selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveEdges.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwapEdges.setText(QtGui.QApplication.translate("GraphViewer", "Swap Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwapEdges.setToolTip(QtGui.QApplication.translate("GraphViewer", "Swaps all the edges between selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwapEdges.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteEdges.setText(QtGui.QApplication.translate("GraphViewer", "Complete Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteEdges.setToolTip(QtGui.QApplication.translate("GraphViewer", "Adds the symetric edge for all edges between the nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteEdges.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeftBipartite.setText(QtGui.QApplication.translate("GraphViewer", "Select Left Bipartite", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeftBipartite.setToolTip(QtGui.QApplication.translate("GraphViewer", "Mark the selected nodes to be used later for a bipartite graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeftBipartite.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteBipartite.setText(QtGui.QApplication.translate("GraphViewer", "Complete Bipartite", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteBipartite.setToolTip(QtGui.QApplication.translate("GraphViewer", "Makes a bipartite graph with the currently selected and the previously selected ones", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteBipartite.setShortcut(QtGui.QApplication.translate("GraphViewer", "Alt+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlViewport.setText(QtGui.QApplication.translate("GraphViewer", "OpenGl", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlViewport.setToolTip(QtGui.QApplication.translate("GraphViewer", "Toggle the viewport to use OpenGl", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardViewport.setText(QtGui.QApplication.translate("GraphViewer", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardViewport.setToolTip(QtGui.QApplication.translate("GraphViewer", "Toggle viewport to use a standard rendering engine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnimations.setText(QtGui.QApplication.translate("GraphViewer", "Animations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAntialiasing.setText(QtGui.QApplication.translate("GraphViewer", "Antialiasing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionText_Antialiasing.setText(QtGui.QApplication.translate("GraphViewer", "Text Antialiasing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmooth_Pixmap_Transform.setText(QtGui.QApplication.translate("GraphViewer", "Smooth Pixmap Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHigh_Quality_Antialiasing.setText(QtGui.QApplication.translate("GraphViewer", "High Quality Antialiasing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("GraphViewer", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setToolTip(QtGui.QApplication.translate("GraphViewer", "Click on nodes to create edges", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setShortcut(QtGui.QApplication.translate("GraphViewer", "Shift+F6", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Function_Viewer.setText(QtGui.QApplication.translate("GraphViewer", "&Function Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandard.setText(QtGui.QApplication.translate("GraphViewer", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("GraphViewer", "&Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("GraphViewer", "&Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setToolTip(QtGui.QApplication.translate("GraphViewer", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJump.setText(QtGui.QApplication.translate("GraphViewer", "&Jump", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJump.setToolTip(QtGui.QApplication.translate("GraphViewer", "Jump", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("GraphViewer", "&Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("GraphViewer", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddType.setText(QtGui.QApplication.translate("GraphViewer", "&Add Type", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardNode.setText(QtGui.QApplication.translate("GraphViewer", "Standard", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PropertyViewer.ui'
#
# Created: Sun May 27 23:28:59 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PropertyViewer(object):
    def setupUi(self, PropertyViewer):
        PropertyViewer.setObjectName(_fromUtf8("PropertyViewer"))
        PropertyViewer.resize(262, 258)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PropertyViewer.sizePolicy().hasHeightForWidth())
        PropertyViewer.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(PropertyViewer)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(PropertyViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 242, 207))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCancel = QtGui.QPushButton(PropertyViewer)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(PropertyViewer)
        self.btnOk.setIconSize(QtCore.QSize(32, 32))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PropertyViewer)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), PropertyViewer.accept)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), PropertyViewer.reject)
        QtCore.QMetaObject.connectSlotsByName(PropertyViewer)

    def retranslateUi(self, PropertyViewer):
        PropertyViewer.setWindowTitle(QtGui.QApplication.translate("PropertyViewer", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("PropertyViewer", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("PropertyViewer", "Ok", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Rules.ui'
#
# Created: Sun May 27 23:28:59 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DgRules(object):
    def setupUi(self, DgRules):
        DgRules.setObjectName(_fromUtf8("DgRules"))
        DgRules.resize(536, 326)
        font = QtGui.QFont()
        font.setKerning(False)
        DgRules.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(DgRules)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(DgRules)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.txeEditRules = QtGui.QTextEdit(DgRules)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.txeEditRules.setFont(font)
        self.txeEditRules.setAcceptRichText(False)
        self.txeEditRules.setObjectName(_fromUtf8("txeEditRules"))
        self.verticalLayout.addWidget(self.txeEditRules)
        self.ptxeException = QtGui.QPlainTextEdit(DgRules)
        self.ptxeException.setMaximumSize(QtCore.QSize(16777215, 80))
        self.ptxeException.setReadOnly(True)
        self.ptxeException.setObjectName(_fromUtf8("ptxeException"))
        self.verticalLayout.addWidget(self.ptxeException)
        self.buttonBox = QtGui.QDialogButtonBox(DgRules)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DgRules)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DgRules.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DgRules.reject)
        QtCore.QMetaObject.connectSlotsByName(DgRules)

    def retranslateUi(self, DgRules):
        DgRules.setWindowTitle(QtGui.QApplication.translate("DgRules", "Rules", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DgRules", "<html><head/><body><p>Enter the attribute rules </p><p>Ex: <span style=\" font-weight:600; color:#55007f;\">if</span> [<span style=\" font-weight:600; color:#0000ff;\">not</span>] Attribute <span style=\" color:#550000;\">is</span> Value [<span style=\" font-weight:600; color:#0000ff;\">and</span> | <span style=\" font-weight:600; color:#0000ff;\">or </span>Attribute <span style=\" font-weight:600; color:#0000ff;\">is </span>Value]* <span style=\" font-weight:600; color:#55007f;\">then</span> Attribute <span style=\" color:#550000;\">is</span> Value </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.txeEditRules.setHtml(QtGui.QApplication.translate("DgRules", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

